### ISSUE TITLE
勝手に良い機能作るのやめてもらっていいですか？？

### ISSUE THREAD

**Issue by c0a21124f8** [c0a2111229/ProjExD#11]
https://github.com/c0a2111229/ProjExD/blob/6b701299fb7912837f90d089c2f7fb6b5d629565/ex03/maze.py#L50
私の彼女というか妻というか家内がその機能良いねって言ってるんですよね～

**Comment by c0a2111229** [comment]
もちゆきやめてもらっていいですか？
