### ISSUE TITLE
逃げろ！こうかとんガチ勢より

### ISSUE THREAD

**Issue by c0a21124f8** [c0a2111229/ProjExD#13]
https://github.com/c0a2111229/ProjExD/blob/4327df3b1b8fd9fbdbf2335d49e77f3017c72bae/ex04/dodge_bomb.py#L78
タイムが表示されるのはTA勢の拙者にとって非常にありがたい機能でござりんちょふ♡
これからもクソ運営と呼ばれないように頑張るべきですな☆

**Comment by c0a2111229** [comment]
ありがとうございます
きっしょいです
